// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpIHnqhXbsr7H9d5FFb_lKdjEyB301UIs',
    appId: '1:915816791919:web:542304fc41fe2e47a4729a',
    messagingSenderId: '915816791919',
    projectId: 'fir-a67e8',
    authDomain: 'fir-a67e8.firebaseapp.com',
    storageBucket: 'fir-a67e8.appspot.com',
    measurementId: 'G-7M46DBJMHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Oi7OKkbkc1Cbj6tG5qOvXGip03gqpew',
    appId: '1:915816791919:android:85b8114a4d6ecdcfa4729a',
    messagingSenderId: '915816791919',
    projectId: 'fir-a67e8',
    storageBucket: 'fir-a67e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5W6N7LncHt28TdsFZXRpWIJIep8LvoYY',
    appId: '1:915816791919:ios:844ec6264f3ada35a4729a',
    messagingSenderId: '915816791919',
    projectId: 'fir-a67e8',
    storageBucket: 'fir-a67e8.appspot.com',
    iosBundleId: 'com.example.femalert2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5W6N7LncHt28TdsFZXRpWIJIep8LvoYY',
    appId: '1:915816791919:ios:ebadcd223cbd3ad3a4729a',
    messagingSenderId: '915816791919',
    projectId: 'fir-a67e8',
    storageBucket: 'fir-a67e8.appspot.com',
    iosBundleId: 'com.example.femalert2.RunnerTests',
  );
}
