name: femalert2
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=3.3.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  flutter_inappwebview: ^5.3.2
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  boxicons: ^2.1.3
  webview_flutter: ^4.7.0
  flutter_phone_direct_caller: ^2.1.1
  google_fonts: ^4.0.3
  dialog_flowtter: ^0.3.3
  http: ^0.13.3
  url_launcher: ^6.1.11
  android_path_provider: ^0.3.0
  shared_preferences: ^2.2.0
  location: ^6.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: PoppinsS
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Italic.ttf
          style: italic
